### ISSUE TITLE
-f appends rather than overwrites

### ISSUE THREAD

**Issue by ardalis** [eduherminio/dotnet-combine#91]
Running this command twice in a row doubles the size of Combined.cs:

```
dotnet-combine single-file . -o Combined.cs -f --exclude "Tests/;obj/;bin/;AssemblyInfo.cs"
```

**Comment by eduherminio** [comment]
Hey @ardalis, first of all, thanks for using `dotnet-combine` and submitting this feedback.

If I'm not mistaken, what's going on here is that subsequent `dotnet-combine single-file` invocations use your `Combined.cs` output file as yet another input file, which in practice duplicates its content.

Could try to add it to the exclusion list or change the output to another directory and see if the problem persists?

Something like:
```bash
dotnet-combine single-file . -o Combined.cs -f --exclude "Tests/;obj/;bin/;AssemblyInfo.cs;Combined.cs"
```
or
```bash
rm Combined.cs
dotnet-combine single-file . -o ../Combined.cs -f --exclude "Tests/;obj/;bin/;AssemblyInfo.cs"
```

**Comment by ardalis** [comment]
Ah that makes sense, thanks. Should it by default ignore the file it's being tasked with overwriting, I wonder?

**Comment by eduherminio** [comment]
> Should it by default ignore the file it's being tasked with overwriting, I wonder?

That's a fair point.

I wouldn't like to add another switch, but I can't see why anyone would like it to be included, so I'll look into just excluding it.

Regarding documentation, we have [this](https://github.com/eduherminio/dotnet-combine#dotnet-combine-single-file-usage-examples), but probably not explicit enough though:
> If you want to merge the source code of MyAmazingProject.csproj, located in C:/MyAmazingProject, you can simply do:
> `dotnet-combine single-file C:/MyAmazingProject`
> That will generated a file under C:/MyAmazingProject/. **_Since having that file there may conflict with your project compilation, you probably want it to be created somewhere else_**, let's say, under C:/tmp/. 
> `dotnet-combine single-file C:/MyAmazingProject --output C:/tmp/`

**Comment by eduherminio** [comment]
Can I ask how did you find this project BTW?
I couldn't help but notice that it's getting more attention/stars in the last 48h than in the previous 2 years 😂😍

**Comment by ardalis** [comment]
CodinGame Fall Challenge just started and one of my coworkers kind it. We used the older approach previously. Thanks for working on it!

**Comment by eduherminio** [comment]
@ardalis [v0.4.0](https://www.nuget.org/packages/dotnet-combine/0.4.0) was just released with a fix for this, file scoped namespaces support and a few more fixes (more info in [release notes](https://github.com/eduherminio/dotnet-combine/releases/tag/v0.4.0))
Please try it out and raise any issues you find!
